name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    #paths: [ "day01/01/" ]
  pull_request:
    branches: [ "main" ]

jobs:
  clang:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: clang
      run: | 
        pwd
        cd day_01/01/
        make clang &> clang_log.txt
        sed '1d' clang_log.txt > temp_file && mv temp_file clang_log.txt

        if [ -s "clang_log.txt" ]; then
            echo "The code is not formatted according to the requirements of the code style"
            exit 1
          else
            echo "OK"
          fi
          cat clang_log.txt
        
  build:
    needs: clang
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        cd day_01/01/
        make build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y libgtest-dev
    - name: modul_test
      working-directory: day_01/01/
      run: make test

      
    - name: functional_test
      working-directory: day_01/01/
      run: |
        make build
        ./main test_imput_01_day.txt
    
    

