name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    #paths: [ "day01/01/" ]
  pull_request:
    branches: [ "main" ]

jobs:
  clang:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: clang
      run: | 
        pwd
        cd day_01/01/
        make clang
        
  build:
    needs: clang
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        cd day_01/01/
        make build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y libgtest-dev
    - name: modul_test
      working-directory: day_01/01/
      run: |
        g++ -o test_program mytest.cpp mylib.cpp  -lgtest -lgtest_main -pthread | tee test_results.log
        cat test_results.log
      #make test | tee test_results.log

      
    - name: functional_test
      working-directory: day_01/01/
      run: |
        make build
        ./main test_imput_01_day.txt
    
    

